name: Test Workkflow
on:
  push:
    branches:
      - 'dev-*'
      - "lead-dev"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code From Rep
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Running the Test
        run: echo "Testing in the Server...."
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code From Rep
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build Website
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Downloaded Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output content
        run: ls
      - name: Deploy
        run: echo "Deploying..."



