name: Beta Workflow
on:
  push:
    branches:
      - 'dev-*'
      - "lead-dev"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code From Rep
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Running the Test
        run: echo "Testing in the Server...."
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{steps.publish.outputs.script-file}}
    steps:
      - name: Get the Code From Rep
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v4 
        with: 
          path: ~/.npm
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install Dependencies
        run: npm ci
      - name: Build Website
        run: npm run build
      - name: Publish JS file name
        id: publish
        run: find dist/assets/*.js -type f -execdir echo '::set-output name=script-file::{}'
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Downloaded Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output content
        run: ls
      - name: Output file name
        run: echo "${{needs.build.outputs.script-file}}"
      - name: Deploy
        run: echo "Deploying..."






